# %%
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score
from sklearn.neural_network import MLPClassifier as MLPC
import time
import warnings

warnings.simplefilter(action='ignore') #Ignore warnings

# %% [markdown]
# # Exercise lecture 8 - Multilayer Perceptron
# Develop an MLP for the MNIST
# database by using the dimension-reduced data from your work on Exercises 2 and 3. You can download the LDA projected data here.
# Further, you can use 10-, 20- and 30-dimensional data generated by PCA and compare
# their performance (at the same time, try various MLP architectures).

# %% [markdown]
# ## Loading data

# %%
def create_complete_datasets(data_dict):
    '''
    Function for creating complete training and test sets containing
    all classes.
    '''
    #Empty list
    trainset = []
    traintargets =[]
    testset = []
    testtargets =[]
    
    #For each class
    for i in range(10):
        trainset.append(data_dict["train%d"%i])
        traintargets.append(np.full(len(data_dict["train%d"%i]),i))
        testset.append(data_dict["test%d"%i])
        testtargets.append(np.full(len(data_dict["test%d"%i]),i))
    
    #Concatenate into to complete datasets
    trainset = np.concatenate(trainset)
    traintargets = np.concatenate(traintargets)
    testset = np.concatenate(testset)
    testtargets = np.concatenate(testtargets)
    return trainset, traintargets, testset, testtargets

file = "mnist_all.mat"
data = loadmat(file)

#Complete training and test sets
train_set, train_targets, test_set, test_targets = create_complete_datasets(data)
train_set = train_set/255
test_set = test_set/255
classes = np.arange(10)

# %% [markdown]
# ## Generating PCA/LDA data
# From previous exercises we already know how to use PCA/LDA.
# We first fit a PCA/LDA model to our training data, and then transform the training and test data using this model, to get a dimensionality reduced data set.

# %%
# PCA modelling first
pcaDimensions = [1,10,20,30,40,50,60,70,80,90,100,200,300,400,500,784] # Sets desired dimensionality/the dimensions which we would iterate through
pcaModels= {} # Creates a dictionary - think of it as a struct in C
for d in pcaDimensions:
    pca=PCA(n_components=d,svd_solver='randomized', random_state=0) # Sets the n variable to be equal the dimensions d
    pca.fit(train_set) # Fits the training data to the PCA model
    pcaModels[d] = pca # Saves it to the dictionary (struct)

# LDA modelling now
ldaComponents = 9 #9 as MNIST contains 10 classes and n-1 is the max amount of components
ldaModel=LDA(n_components=ldaComponents)
ldaModel.fit(train_set, train_targets) # Fits across full training set

# %% [markdown]
# ## Creating and Training MLP
# Sklearn has a multilayer perceptron classifier which we can use:
# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html 
# 
# To use it, we need to choose how many layers we would like to use and the size of each hidden layer. 
# We can also choose which non-linear activation function to use and what optimizer/solver to use.
# You can set a maximum iteration number as well (to limit compute time).

# Trying several different MLP architectures for shits and giggles:
mlpArchitectures = {
    "small": (64,),            # 64 hidden units single layer
    "medium": (128,),          # 128 single layer
    "wideShallow": (256,),    # 256 single layer
    "twoLayer": (128, 64),    # two-layer network
    "mnistOptimal": (784,),     # Single layer containing all 28x28 variables 
    "deep": (128,64,64,64,),
    "deeper": (64,64,64,64,64,64,64,),
    "twoLayerBottleNeck": (512,256,),
    "threeLayerBottleNeck": (512,256,128,),
    "wideDeep": (256,128,),
    "shallowTaper": (512,256,128,64,),
    "deepTaper": (512,256,128,64,32,16,8,4,2),
    "wikiWork": (784, 800,)

    #"2mnist2optimal": (784,784)
    #"deepMnistOptimal": (784,784,784,784,784,784,784,784,784,784) # This is gonna take some time, comment me out unless you've got a lot of time
}

# MLPClassifier parameters as 1 instead of re-filling:
mlpParams = {
    "activation": "relu",
    "solver": "adam",
    "alpha": 1e-4,            # L2 penalty (regularization)
    "batch_size": 256,
    "max_iter": 200,
    "early_stopping": True,
    "n_iter_no_change": 10,
    "random_state": 0,
    "verbose": False
}

#Helper function for training and evaluating each MLP
def trainEval(xTrain,yTrain,xTest,yTest,hiddenLayers,mlpParams):
    clf = MLPC(hidden_layer_sizes=hiddenLayers, **mlpParams)
    startTime= time.time() # For timing the execution
    clf.fit(xTrain,yTrain) # Actually trains
    endTime= time.time() # Time when training is done
    trainingTime=endTime-startTime
    yPrediction=clf.predict(xTest)
    Accuracy=accuracy_score(yTest,yPrediction) # Uses sklearn function for scoring
    return clf, Accuracy, trainingTime, yPrediction

# Lets run some tests:
resultDict = {} # Creates a struct in which results and associated data is stored

#PCA first again:
for d in pcaDimensions:
    pca = pcaModels[d]
    xTrainPCA = pca.transform(train_set)
    xTestPCA = pca.transform(test_set)
    key = f"PCA{d}"
    resultDict[key]={}
    for name, architecture, in mlpArchitectures.items():
        clf, Accuracy, trainingTime, yPrediction = trainEval(xTrainPCA,train_targets,xTestPCA,test_targets,architecture,mlpParams)
        resultDict[key][name]={
             "Architecture: ":architecture, "Accuracy: ": Accuracy, "Time Spend: ": trainingTime, "Classifier: ": clf, "Y Prediction: ": yPrediction, "X Train Shape: ": xTrainPCA.shape
        }
        print(f"PCA {d:2d} | {name:12s} | architecture={architecture} | Accuracy={Accuracy:.4f} | time= {trainingTime:.1f}s")

# Then LDA:
xTrainLDA=ldaModel.transform(train_set)
xTestLDA=ldaModel.transform(test_set)

resultDict["LDA:"] = {}
for name, architecture, in mlpArchitectures.items():
    clf, Accuracy, trainingTime, yPrediction = trainEval(xTrainLDA,train_targets,xTestLDA,test_targets,architecture,mlpParams)
    resultDict["LDA:"][name]={
        "Architecture: ":architecture, "Accuracy: ": Accuracy, "Time Spend: ": trainingTime, "Classifier: ": clf, "Y Prediction: ": yPrediction, "X Train Shape: ": xTrainLDA.shape
    }
    print(f"LDA | {name:12s} | architecture={architecture} | Accuracy={Accuracy:.4f} | time= {trainingTime:.1f}s")

# Overseeable summary between PCA and LDA
summary = []
for dataset in resultDict:
    bestName, bestInfo = max(resultDict[dataset].items(), key=lambda kv: kv[1]['Accuracy: '])
    summary.append((dataset, bestName, bestInfo['Architecture: '], bestInfo['Accuracy: '], bestInfo['Time Spend: ']))
    print(f"{dataset:8s} Best: {bestName:12s} architecture={bestInfo['Architecture: ']} Accuracy={bestInfo['Accuracy: ']:.4f} time= {bestInfo['Time Spend: ']:.1f}s")

# Confusion matrices:
nPlots = len(resultDict)
nCols = 2
nRows = int(np.ceil(nPlots/nCols))
plt.figure(figsize=(10,5*nRows))

i = 1
for dataset in sorted(resultDict.keys()):
    bestName, bestInfo = max(resultDict[dataset].items(), key=lambda kv: kv[1]['Accuracy: '])
    yPrediction = bestInfo['Y Prediction: ']
    confusionMatrix = confusion_matrix(test_targets, yPrediction, labels=classes)
    plt.subplot(nRows, nCols, i)
    display = ConfusionMatrixDisplay(confusion_matrix=confusionMatrix, display_labels=classes)
    display.plot(values_format='d', cmap=plt.cm.Blues, ax=plt.gca(), colorbar=False)
    plt.title(f"{dataset} | {bestName} | Accuracy={bestInfo['Accuracy: ']:.3f}")
    plt.tight_layout()
    i += 1

plt.show()

print("\nShort conclusions:")
# pick highest overall
allBest = []
for dataset in resultDict:
    name, info = max(resultDict[dataset].items(), key=lambda kv: kv[1]['Accuracy: '])
    allBest.append((dataset, name, info['Accuracy: ']))
allBestSorted = sorted(allBest, key=lambda t: t[2], reverse=True)
for ds, nm, Accuracy in allBestSorted:
    print(f"- {ds:8s} best model {nm:12s} => test Accuracy: {Accuracy:.4f}")

print("\nNotes:")
print("LDA uses at most 9 components (n_classes - 1). It often preserves class-separating directions beneficial for linear classifiers and may help MLPs.")
print("PCA retains variance; increasing PCA dims (10->50) usually improves accuracy but with diminishing returns.")
print("Tuning architectures, learning rate and regularization (alpha) for better accuracy.")
print("If training is slow, reduce hidden layer sizes, increase batch_size, or lower max_iter/enable early_stopping (already enabled here).")

# %% [markdown]
# ### Model trained on LDA data

# %%
# Instantiate MLP with your parameters of choice and train it on the LDA dimensionality reduced training data.
# Afterwards test it on the test data

# %% [markdown]
# ### Model trained on PCA data

# %%
# Instantiate MLP with your parameters of choice and train it on the PCA dimensionality reduced training data.
# Afterwards test it on the test data

# %% [markdown]
# ## Comparing the trained models
# With models trained on both LDA and PCA data, let's compare them using the confusion matrices.

# %%
#%%Confusion matrix
#Compute the confusion matrices for both MLPs (trained on PCA and LDA) and plot

# %% [markdown]
# ### What can we conclude from the comparison?
# 


